name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_CLIENT_ID: dummy_id
      GITHUB_CLIENT_SECRET: dummy_secret
      PUBLIC_GITHUB_OWNER: ${{ vars.GITHUB_OWNER }}
      PUBLIC_GITHUB_REPO: ${{ vars.GITHUB_REPO }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Type check
        run: bun run check
