name: Deploy

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_CLIENT_ID: ${{ secrets.CF_GITHUB_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.CF_GITHUB_CLIENT_SECRET }}
      PUBLIC_GITHUB_OWNER: ${{ vars.GITHUB_OWNER }}
      PUBLIC_GITHUB_REPO: ${{ vars.GITHUB_REPO }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .svelte-kit/cloudflare --project-name=pexisgle-dev
